// <auto-generated />
using System;
using MarketPulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketPulse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketPulseDbContext))]
    [Migration("20260805030720_Slice5aPortfolio")]
    partial class Slice5aPortfolio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketPulse.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal?>("TriggeredPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset?>("TriggeredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Ticker", "Status");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("TriggeredPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("DispatchedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredUtc")
                        .HasDatabaseName("IX_OutboxMessages_Pending")
                        .HasFilter("[DispatchedUtc] IS NULL");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastTradedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.Ticker", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("SeedPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Code");

                    b.ToTable("Tickers");

                    b.HasData(
                        new
                        {
                            Code = "IVV",
                            Name = "iShares S&P 500 ETF",
                            SeedPrice = 62.10m
                        },
                        new
                        {
                            Code = "NDQ",
                            Name = "BetaShares NASDAQ 100 ETF",
                            SeedPrice = 54.30m
                        },
                        new
                        {
                            Code = "VHY",
                            Name = "Vanguard Australian Shares High Yield",
                            SeedPrice = 68.75m
                        },
                        new
                        {
                            Code = "FANG",
                            Name = "Global X FANG+ ETF",
                            SeedPrice = 26.40m
                        },
                        new
                        {
                            Code = "VAS",
                            Name = "Vanguard Australian Shares Index",
                            SeedPrice = 98.20m
                        },
                        new
                        {
                            Code = "A200",
                            Name = "BetaShares Australia 200 ETF",
                            SeedPrice = 142.60m
                        },
                        new
                        {
                            Code = "VGS",
                            Name = "Vanguard MSCI Intl Shares Index",
                            SeedPrice = 125.90m
                        },
                        new
                        {
                            Code = "IOZ",
                            Name = "iShares Core S&P/ASX 200 ETF",
                            SeedPrice = 34.85m
                        },
                        new
                        {
                            Code = "STW",
                            Name = "SPDR S&P/ASX 200 Fund",
                            SeedPrice = 74.90m
                        },
                        new
                        {
                            Code = "VAP",
                            Name = "Vanguard Australian Property Securities",
                            SeedPrice = 88.40m
                        },
                        new
                        {
                            Code = "VAF",
                            Name = "Vanguard Australian Fixed Interest",
                            SeedPrice = 45.15m
                        },
                        new
                        {
                            Code = "IOO",
                            Name = "iShares Global 100 ETF",
                            SeedPrice = 140.25m
                        },
                        new
                        {
                            Code = "QUAL",
                            Name = "VanEck MSCI Intl Quality ETF",
                            SeedPrice = 48.70m
                        },
                        new
                        {
                            Code = "ETHI",
                            Name = "BetaShares Global Sustainability",
                            SeedPrice = 14.55m
                        },
                        new
                        {
                            Code = "HACK",
                            Name = "BetaShares Global Cybersecurity ETF",
                            SeedPrice = 12.30m
                        },
                        new
                        {
                            Code = "ACDC",
                            Name = "Global X Battery Tech & Lithium ETF",
                            SeedPrice = 72.15m
                        },
                        new
                        {
                            Code = "ASIA",
                            Name = "BetaShares Asia Technology Tigers ETF",
                            SeedPrice = 11.85m
                        },
                        new
                        {
                            Code = "GEAR",
                            Name = "BetaShares Geared Australian Equity",
                            SeedPrice = 32.40m
                        },
                        new
                        {
                            Code = "MOAT",
                            Name = "VanEck Morningstar Wide Moat ETF",
                            SeedPrice = 118.90m
                        },
                        new
                        {
                            Code = "IHVV",
                            Name = "iShares S&P 500 AUD Hedged ETF",
                            SeedPrice = 46.55m
                        },
                        new
                        {
                            Code = "VTS",
                            Name = "Vanguard US Total Market Shares",
                            SeedPrice = 410.30m
                        },
                        new
                        {
                            Code = "VEU",
                            Name = "Vanguard All-World ex-US Shares",
                            SeedPrice = 94.20m
                        },
                        new
                        {
                            Code = "SLF",
                            Name = "SPDR S&P/ASX 200 Listed Property",
                            SeedPrice = 13.75m
                        },
                        new
                        {
                            Code = "SYI",
                            Name = "SPDR MSCI Australia Select High Div",
                            SeedPrice = 29.60m
                        },
                        new
                        {
                            Code = "RBTZ",
                            Name = "Global X ROBO Global Robotics ETF",
                            SeedPrice = 21.05m
                        });
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("RecordedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId", "OccurredUtc");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "dev@marketpulse.local",
                            FailedLoginCount = 0,
                            PasswordHash = "AQAAAAIAAYagAAAAEIoGPGaPOO/1jvXR2HrOQV5cvQDBSIo1eWEg7F7xGnD2nlgaoh4kmq9+42csuJnjAw=="
                        });
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Watchlists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.AlertRule", b =>
                {
                    b.HasOne("MarketPulse.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MarketPulse.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("MarketPulse.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("MarketPulse.Domain.Entities.Holding", "_holdings", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AverageCost")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<Guid>("PortfolioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("RealisedPnL")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<string>("Ticker")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.Property<decimal>("Units")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)");

                            b1.HasKey("Id");

                            b1.HasIndex("PortfolioId", "Ticker")
                                .IsUnique();

                            b1.ToTable("Holdings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PortfolioId");
                        });

                    b.Navigation("_holdings");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MarketPulse.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("MarketPulse.Domain.Entities.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.Watchlist", b =>
                {
                    b.HasOne("MarketPulse.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("MarketPulse.Domain.Entities.WatchlistItem", "_items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("AddedUtc")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Ticker")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.Property<Guid>("WatchlistId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("WatchlistId", "Ticker")
                                .IsUnique();

                            b1.ToTable("WatchlistItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WatchlistId");

                            b1.HasData(
                                new
                                {
                                    Id = new Guid("33333333-3333-3333-3333-333333333001"),
                                    AddedUtc = new DateTimeOffset(new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                                    Ticker = "IVV",
                                    WatchlistId = new Guid("22222222-2222-2222-2222-222222222222")
                                },
                                new
                                {
                                    Id = new Guid("33333333-3333-3333-3333-333333333002"),
                                    AddedUtc = new DateTimeOffset(new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                                    Ticker = "NDQ",
                                    WatchlistId = new Guid("22222222-2222-2222-2222-222222222222")
                                },
                                new
                                {
                                    Id = new Guid("33333333-3333-3333-3333-333333333003"),
                                    AddedUtc = new DateTimeOffset(new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                                    Ticker = "VHY",
                                    WatchlistId = new Guid("22222222-2222-2222-2222-222222222222")
                                },
                                new
                                {
                                    Id = new Guid("33333333-3333-3333-3333-333333333004"),
                                    AddedUtc = new DateTimeOffset(new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                                    Ticker = "FANG",
                                    WatchlistId = new Guid("22222222-2222-2222-2222-222222222222")
                                });
                        });

                    b.Navigation("_items");
                });
#pragma warning restore 612, 618
        }
    }
}
