// <auto-generated />
using System;
using MarketPulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketPulse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketPulseDbContext))]
    partial class MarketPulseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketPulse.Domain.Entities.Ticker", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("SeedPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Code");

                    b.ToTable("Tickers");

                    b.HasData(
                        new
                        {
                            Code = "IVV",
                            Name = "iShares S&P 500 ETF",
                            SeedPrice = 62.10m
                        },
                        new
                        {
                            Code = "NDQ",
                            Name = "BetaShares NASDAQ 100 ETF",
                            SeedPrice = 54.30m
                        },
                        new
                        {
                            Code = "VHY",
                            Name = "Vanguard Australian Shares High Yield",
                            SeedPrice = 68.75m
                        },
                        new
                        {
                            Code = "FANG",
                            Name = "Global X FANG+ ETF",
                            SeedPrice = 26.40m
                        },
                        new
                        {
                            Code = "VAS",
                            Name = "Vanguard Australian Shares Index",
                            SeedPrice = 98.20m
                        },
                        new
                        {
                            Code = "A200",
                            Name = "BetaShares Australia 200 ETF",
                            SeedPrice = 142.60m
                        },
                        new
                        {
                            Code = "VGS",
                            Name = "Vanguard MSCI Intl Shares Index",
                            SeedPrice = 125.90m
                        },
                        new
                        {
                            Code = "IOZ",
                            Name = "iShares Core S&P/ASX 200 ETF",
                            SeedPrice = 34.85m
                        },
                        new
                        {
                            Code = "STW",
                            Name = "SPDR S&P/ASX 200 Fund",
                            SeedPrice = 74.90m
                        },
                        new
                        {
                            Code = "VAP",
                            Name = "Vanguard Australian Property Securities",
                            SeedPrice = 88.40m
                        },
                        new
                        {
                            Code = "VAF",
                            Name = "Vanguard Australian Fixed Interest",
                            SeedPrice = 45.15m
                        },
                        new
                        {
                            Code = "IOO",
                            Name = "iShares Global 100 ETF",
                            SeedPrice = 140.25m
                        },
                        new
                        {
                            Code = "QUAL",
                            Name = "VanEck MSCI Intl Quality ETF",
                            SeedPrice = 48.70m
                        },
                        new
                        {
                            Code = "ETHI",
                            Name = "BetaShares Global Sustainability",
                            SeedPrice = 14.55m
                        },
                        new
                        {
                            Code = "HACK",
                            Name = "BetaShares Global Cybersecurity ETF",
                            SeedPrice = 12.30m
                        },
                        new
                        {
                            Code = "ACDC",
                            Name = "Global X Battery Tech & Lithium ETF",
                            SeedPrice = 72.15m
                        },
                        new
                        {
                            Code = "ASIA",
                            Name = "BetaShares Asia Technology Tigers ETF",
                            SeedPrice = 11.85m
                        },
                        new
                        {
                            Code = "GEAR",
                            Name = "BetaShares Geared Australian Equity",
                            SeedPrice = 32.40m
                        },
                        new
                        {
                            Code = "MOAT",
                            Name = "VanEck Morningstar Wide Moat ETF",
                            SeedPrice = 118.90m
                        },
                        new
                        {
                            Code = "IHVV",
                            Name = "iShares S&P 500 AUD Hedged ETF",
                            SeedPrice = 46.55m
                        },
                        new
                        {
                            Code = "VTS",
                            Name = "Vanguard US Total Market Shares",
                            SeedPrice = 410.30m
                        },
                        new
                        {
                            Code = "VEU",
                            Name = "Vanguard All-World ex-US Shares",
                            SeedPrice = 94.20m
                        },
                        new
                        {
                            Code = "SLF",
                            Name = "SPDR S&P/ASX 200 Listed Property",
                            SeedPrice = 13.75m
                        },
                        new
                        {
                            Code = "SYI",
                            Name = "SPDR MSCI Australia Select High Div",
                            SeedPrice = 29.60m
                        },
                        new
                        {
                            Code = "RBTZ",
                            Name = "Global X ROBO Global Robotics ETF",
                            SeedPrice = 21.05m
                        });
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.Watchlist", b =>
                {
                    b.HasOne("MarketPulse.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("MarketPulse.Domain.Entities.WatchlistItem", "_items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("AddedUtc")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Ticker")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.Property<Guid>("WatchlistId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("WatchlistId", "Ticker")
                                .IsUnique();

                            b1.ToTable("WatchlistItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WatchlistId");
                        });

                    b.Navigation("_items");
                });
#pragma warning restore 612, 618
        }
    }
}
